import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { React, useState } from "react";
import { ethers } from "ethers";
import {buyTokens, balanceOf} from '../init';

export default function BuyTokens() {
  const [errorMessage, setErrorMessage] = useState(null);
  const [defaultAccount, setDefaultAccount] = useState(null);
  const [connButtonText, setConnButtonText] = useState("Connect Wallet");

  const connectWalletHandler = () => {
    if (typeof window !== "undefined") {
      window.ethereum.on("accountsChanged", accountChangedHandler);
      window.ethereum.on("chainChanged", chainChangedHandler);
    }
    if (window.ethereum && window.ethereum.isMetaMask) {
      window.ethereum
        .request({ method: "eth_requestAccounts" })
        .then((result) => {
          accountChangedHandler(result[0]);
          setConnButtonText("Wallet Connected");
        })
        .catch((error) => {
          setErrorMessage(error.message);
        });
    } else {
      console.log("Need to install MetaMask");
      setErrorMessage("Please install MetaMask browser extension to interact");
    }
  };

  const accountChangedHandler = (newAccount) => {
    setDefaultAccount(newAccount);
  };

  const chainChangedHandler = () => {
    window.location.reload();
  };

  if (typeof window !== "undefined") {
    window.ethereum.on("accountsChanged", accountChangedHandler);
    window.ethereum.on("chainChanged", chainChangedHandler);
  }

  return (
    <div
      style={{
        backgroundColor: "grey",
      }}
      className={styles.container}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Testing Interaction</h1>

        <div className={styles.card}>
          <button onClick={connectWalletHandler}>{connButtonText}</button>

          <h3> Wallet Address:{defaultAccount}</h3>
        </div>

        <div className={styles.card}>
        <label for="buyTokensAddress">To Address: </label>
          <input className={styles.grid} type="text" id="buyTokensAddress" name="buyTokensAddress" />
        <label for="buyTokensAmount">Token amount: </label>
          <input className={styles.grid} type="text" id="buyTokensAmount" name="buyTokensAmount" />
          <button onClick={buyTokens}>Buy Tokens</button>
          <div id="buyTokens"> </div>
          <div id="buyTokensFunc"> </div>
        </div>

        <div className={styles.card}>
          <label for="balanceOfTokenAddress">Address: </label>
          <input className={styles.grid} type="text" id="balanceOfTokenAddress" name="first" />
          <button onClick={balanceOf}> Get Token Balance</button>
          <div id="balanceOf"> </div>
          <div id="balanceOfFunc"> </div>
          </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
