import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// import { ethers } from "ethers";

// import { useWeb3 } from "@3rdweb/hooks";
// import { inits } from "../init";

export default function BuyToken() {
  // const { address, connectWallet } = useWeb3();
const rpcURL = "https://eth-goerli.g.alchemy.com/v2/5ke_aBT8DJvT329K4K-in812_DJs1w9d";
const alchemyAPI_KEY = "5ke_aBT8DJvT329K4K-in812_DJs1w9d";

async function inits(){
    let provider;
    let selectedAccount;
    // window.ethereum
    try {
        provider = window.ethereum;
        if (typeof provider !== "undefined") {
            provider.request({ method: "eth_requestAccounts" }).then((accounts) => {
                selectedAccount = accounts[0];
                console.log(selectedAccount);
            }).catch((err) => {
                console.log(err);
                return;
            })
          
        }
    } catch (e) {
        // provider = new Web3.providers.HttpProvider(rpcURL);
        console.log("no metamask", e)
    }
    // const etherprovider = new ethers.providers.AlchemyProvider('goerli', config.alchemyAPI_KEY);
    // const signer = new ethers.Wallet(config.privateKey, etherprovider);
  
  }


  return (
    <div
      style={{
        backgroundColor: "grey",
      }}
      className={styles.container}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Testing Interaction</h1>

        <div className={styles.card}>

  
          <button  onClick={inits}> Connect </button>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
